-- 005: Adds the FamilyAccessTokens table used by the Family API for
-- token-based authentication (JWT login/refresh).
--
-- TokenSecret stores "<salt>$<sha256(salt + secret) hex>" — never the plaintext
-- secret. Secrets are generated by the API (POST /tokens) or by
-- family.api/scripts/create-db.js.
--
-- FamilyIdGroupRights is a comma separated list of FamilyGroupIds the token
-- may access; NULL, '' or '*' grants access to every family group.
--
-- The API also auto-creates this table at startup (CREATE TABLE IF NOT EXISTS),
-- so this migration is only needed when updating a DB file by hand.

CREATE TABLE IF NOT EXISTS FamilyAccessTokens (
    TokenId              INTEGER PRIMARY KEY AUTOINCREMENT,
    Name                 TEXT NOT NULL,
    TokenSecret          TEXT NOT NULL,
    IsAdmin              INTEGER NOT NULL DEFAULT 0,
    HasWriteRights       INTEGER NOT NULL DEFAULT 0,
    Expires              TEXT,
    FamilyIdGroupRights  TEXT,
    IsDeleted            INTEGER NOT NULL DEFAULT 0
);
